package installer

import (
	"context"
	"errors"
	"io"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

type bootstrapFailureRunner struct{ calls []string }

func (r *bootstrapFailureRunner) Run(_ context.Context, name string, args ...string) error {
	r.calls = append(r.calls, name+" "+strings.Join(args, " "))
	if len(args) > 0 && args[0] == "bootstrap" {
		return errors.New("bootstrap exit status 5")
	}
	return nil
}

func TestLaunchAgentBootstrapFailureStopsInstall(t *testing.T) {
	runner := &bootstrapFailureRunner{}
	installer := engine{options: Options{Runner: runner, Stdout: io.Discard}, apply: true}
	err := installer.reloadLaunchAgentWithLabel(context.Background(), "/fixture/agent.plist", mcpLaunchdLabel)
	if err == nil || !strings.Contains(err.Error(), "bootstrap") {
		t.Fatalf("bootstrap failure=%v, want actionable error", err)
	}
	if len(runner.calls) != 2 || !strings.Contains(runner.calls[0], "bootout") {
		t.Fatalf("calls=%q", runner.calls)
	}
}

func TestRetirementReachesSecondaryClaudeAndCodex(t *testing.T) {
	home := t.TempDir()
	primary := filepath.Join(home, ".claude")
	secondary := filepath.Join(home, "account-two")
	codexHome := filepath.Join(home, ".codex")
	managed := filepath.Join(home, "install")
	status := filepath.Join(secondary, "statusline-command.sh")
	if err := os.MkdirAll(secondary, 0700); err != nil {
		t.Fatal(err)
	}
	if err := os.Symlink(filepath.Join(primary, "gone-statusline.sh"), status); err != nil {
		t.Fatal(err)
	}
	agent := filepath.Join(codexHome, "agents", "frr.toml")
	writeFixture(t, agent, "# Generated by pfm codex build from /fixture/templates/global/agents/frr.md; do not edit.\nname = \"frr\"\n")
	swap := filepath.Join(managed, "swap.command.md")
	writeFixture(t, swap, "Run `pfm chat swap`\n")
	installer := engine{options: Options{Home: home, ConfigDir: primary, ConfigDirs: []string{primary, secondary}, CodexHomes: []string{codexHome}, Stdout: io.Discard}, managedRoot: managed, apply: true}
	for _, run := range []func() error{installer.retirePredecessors, installer.retireRenamedGlobalAgents, installer.retireLegacySwapCommand} {
		if err := run(); err != nil {
			t.Fatal(err)
		}
	}
	for _, path := range []string{status, agent, swap} {
		if _, err := os.Lstat(path); !errors.Is(err, os.ErrNotExist) {
			t.Errorf("retired artifact %s survives: %v", path, err)
		}
	}
}
